contactform:
  title: Get in Touch
  text: I'd love to hear from you.
  button: Send

social:
  github: foo
  linkedin: foo
  twitter: foo
  facebook: foo
  googleplus: foo
  dribbble: foo
  pinterest: foo
  instagram: foo
